### PR TITLE
Upgrade to latest js-threads (next) release

### PR DESCRIPTION
**Pull request by carsonfarmer**
Signed-off-by: Carson Farmer <carson.farmer@gmail.com>

## Description

This is an initial upgrade PR that pulls in "next" releases from @textile/threads and friends.

### CODE REVIEW

**Review by andrewxhill — COMMENTED** [review]
i can't recall, is this gtg w/ production or would it be blocking js-hub release?

**Comment by carsonfarmer** [comment]
It _is_ actually good to go, but it would be better to get a js-threads release in here first before doing a hub release.

**Comment by carsonfarmer** [comment]
I'm hoping to have a js-threads released done by eod.

**Comment by andrewxhill** [comment]
rebase and that test will pass

**Comment by carsonfarmer** [comment]
Cool. So this all passes and looks to be ready for release. We should merge this one, and then promote those threads packages from "next" to "latest". I can do that after the fact though.

**Review by andrewxhill — APPROVED** [review]

**Pull request merged**
